stages:
  - test
  - package
  - release

# Run the tests only on commits, never on tags for now this just builds the
# release archives to make sure that works
test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH
  image: alpine:3
  before_script:
    - echo PACKAGE_JOB_ID=$CI_JOB_ID >> package.env
    - apk add xz 7zip make
  script:
    - make

# Build the release archives and keep them forever as an artifact. Only runs on
# tag pushes
package:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
  image: alpine:3
  before_script:
    - echo PACKAGE_JOB_ID=$CI_JOB_ID >> package.env
    - apk add xz 7zip make
  script:
    - make
  image: alpine:3
  before_script:
    - echo PACKAGE_JOB_ID=$CI_JOB_ID >> package.env
    - apk add xz 7zip make
  script:
    - make
  artifacts:
    expire_in: never
    paths:
      - release/mercator.zip
      - release/mercator.tar.gz
      - release/mercator.tar.xz
    reports:
      dotenv: package.env

# Create a release with the previously generated artifacts. Only runs on tag
# pushes
release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'Creating release'
  needs:
    - job: package
      artifacts: true
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Mercator $CI_COMMIT_TAG'
    description: 'Mercator $CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Mercator Addon (zip archive)'
          url: 'https://gitlab.com/mercator-wow/mercator/-/jobs/${PACKAGE_JOB_ID}/artifacts/raw/release/mercator.zip'
        - name: 'Mercator Addon (tar.xz archive)'
          url: 'https://gitlab.com/mercator-wow/mercator/-/jobs/${PACKAGE_JOB_ID}/artifacts/raw/release/mercator.tar.xz'
        - name: 'Mercator Addon (tar.gz archive)'
          url: 'https://gitlab.com/mercator-wow/mercator/-/jobs/${PACKAGE_JOB_ID}/artifacts/raw/release/mercator.tar.gz'
