name: Test Commit
on:
  push:
    branches:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build release archives
        run: make
